-- lune needs to be able to read this file
-- so do not use roblox data types

return {
	CompactToolbarButton = false,
	AllowExperimentalMode = true,

	TileHighResImagesEnabled = true,
	TileHighResImagesSize = { X = 1024, Y = 1024 },
	MaxCaptureRectSize = { X = 2048, Y = 2048 },

	GalleryImageControlsEnabled = true,

	DockWidgetSize = { X = 500, Y = 350 },
	ConfigWindowSize = { X = 260, Y = 320 },
}
