local Types = require(script.Types)
local Wally = require(script.Wally)
local Binding = require(script.Binding)

local RenderRect = require(script.Helpers.RenderRect)
local Reversible = require(script.Helpers.Reversible)
local CachelessRequire = require(script.Helpers.CachelessRequire)

local Bindings = {}

export type UICaptureTypes = Types.UICaptureTypes
export type ViewportCaptureTypes = Types.ViewportCaptureTypes

export type CaptureViewportOptions = Types.CaptureViewportOptions
export type CaptureUIOptions = Types.CaptureUIOptions

export type RequestRectOptions = Types.RequestRectOptions

-- Public

Bindings.rect = RenderRect
Bindings.reversible = Reversible.wrap

function Bindings.execute(script: LuaSourceContainer)
	assert(game:GetService("CoreGui"), "This should only be run in the command line.")
	return CachelessRequire.execute(script, {})
end

function Bindings.getVersion(): string
	return Binding.invoke("getVersion")
end

function Bindings.getPackageVersion(): string
	return assert(script:GetAttribute("PackageVersion") :: string?, "No package version attribute found.")
end

function Bindings.getOSScale(): Vector2
	return Binding.invoke("getOSScale")
end

function Bindings.yieldUntilNextFrame(): ()
	return Binding.invoke("yieldUntilNextFrame")
end

function Bindings.getMeshPart(): MeshPart
	return Binding.invoke("getMeshPart")
end

function Bindings.captureViewport(options: CaptureViewportOptions): MeshPart?
	return Binding.invoke("captureViewport", options)
end

function Bindings.captureUI(options: CaptureUIOptions): MeshPart?
	return Binding.invoke("captureUI", options)
end

function Bindings.requestRect(options: RequestRectOptions)
	local guid: string = Binding.invoke("requestRect", {
		type = "request",
		rect = options.rect,
		scale = options.scale,
	})

	local cachedResult
	local resolvedExpect = false
	local resolvedCancel = false

	local function expect()
		if not resolvedExpect and not resolvedCancel then
			resolvedExpect = true
			cachedResult = Binding.invoke("requestRect", {
				type = "expect",
				guid = guid,
			}) :: Rect?
		end
		return cachedResult
	end

	local function cancel()
		if not resolvedCancel then
			resolvedCancel = true
			Binding.invoke("requestRect", {
				type = "cancel",
				guid = guid,
			})
		end
	end

	return expect, cancel
end

function Bindings.isConnected(): boolean
	return Binding.isConnected()
end

function Bindings.isCompatible(): boolean
	local pkgVersion = Wally.package.version
	return Binding.invoke("compatibilityCheck", pkgVersion)
end

return Bindings
